### ISSUE TITLE
How do i import this library

### ISSUE THREAD

**Issue by haoyu234** [projectitis/jx#4]
I currently write like this
```haxe
import src.haxe.JxParser;
```

but the compiler prompts an error.
```
`package;` in /haxe/lib/jx/git/src/haxe/JxParser.hx should be `package src.haxe;`
```

**Comment by projectitis** [comment]
Hi there. This is my own library and is not part of Haxe itself. You need to download the jx code and add it to your project path. Then see one of the examples for the correct import statement :)
